# Generated by Django 5.1.3 on 2024-11-25 10:00

import app_image_processing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_image_processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to=app_image_processing.models.generate_image_filename),
        ),
    ]
